import type { InitialTvChannelSeed } from './types';

export const LUAN9X_CHANNELS_PART_4: readonly InitialTvChannelSeed[] = [
  { canonicalKey: "tv:2-14mvp1z", name: "Հ2", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "H2.am", logoUrl: "https://i.imgur.com/fMOopjK.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-d980459ab8-1yfc8dc", name: "Շանթ", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "ShantTV.am", logoUrl: "https://i.imgur.com/tUQ8vQT.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-b87390db8d-64u8b7", name: "Արմենիա", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "ArmeniaTV.am", logoUrl: "https://i.imgur.com/EqkF0O8.jpg", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-f83dbd9912-14ro45c", name: "Կենտրոն", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "KentronTV.am", logoUrl: "https://i.imgur.com/SrHncfk.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:5-1th2ibn", name: "5-րդ ալիք", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "5TVArmenia.am", logoUrl: "https://i.imgur.com/TejnGpV.jpg", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-18124a58ae-k2a0uz", name: "Երկիր Մեդիա", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "YerkirMediaTV.am", logoUrl: "https://i.imgur.com/FKpxkVH.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:atv-armenia-1gph48t", name: "ATV Armenia", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "atv-armenia", logoUrl: "https://i.imgur.com/A3bmTWO.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:21-ged3wn", name: "Դար 21", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "21TV.am", logoUrl: "https://i.imgur.com/NV6ZeW9.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-b7853c2f21-ydnn6z", name: "Արմնյուզ", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmNews.am", logoUrl: "https://i.imgur.com/0vrFGY5.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-d9fd232ea8-1gba29d", name: "Նոր Հայաստան", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "NorHayastanTV.am", logoUrl: "https://i.imgur.com/EmOsMTC.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-cddf488b99-fc6eoa", name: "Շողակաթ", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ShoghakatTV.am", logoUrl: "https://i.imgur.com/e4VxCnn.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:armenia-premium-s6k8jl", name: "Armenia Premium", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmeniaPremium.am", logoUrl: "https://i.imgur.com/IxOFvqz.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-2184249e7b-y7pogv", name: "Հայ Կինո", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmeniaHayKino.am", logoUrl: "https://i.imgur.com/XwbLfqd.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:tv-b200yt", name: "Ջան TV", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmeniaJanTV.am", logoUrl: "https://i.imgur.com/AhX46e5.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-ca8511f830-2x0473", name: "Քոմեդի", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmeniaKomedi.am", logoUrl: "https://i.imgur.com/pvF7dGN.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-dbde9820b0-ehtjth", name: "Տուն Թունիկ", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmeniaTownTownik.am", logoUrl: "https://i.imgur.com/XjhkUXy.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-5f17626775-e17p78", name: "Սինեմաքս", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ArmeniaSinemaks.am", logoUrl: "https://i.imgur.com/fRfGuQg.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:tv-1xwd7nw", name: "Թավա TV", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ATVTavaTV.am", logoUrl: "https://i.imgur.com/cndJCRU.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:tv-790ak1", name: "ԽաղԱլիք TV", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ATVKhaghaliqTV.am", logoUrl: "https://i.imgur.com/mrfm9uY.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:tv-ah3y6q", name: "Կինոման TV", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ATVKinoman.am", logoUrl: "https://i.imgur.com/lidNHkH.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:tv-75e8zx", name: "Հայ TV", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "ATVHayTV.am", logoUrl: "https://i.imgur.com/KCkzU5R.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:channel-d9ed203ce3-11e5o0i", name: "Ֆիլմզոն", groupSlug: "west-asia", sourceGroup: "Tây Á", tvgId: "ATVFilmzone.am", logoUrl: "https://i.imgur.com/uWBrDpV.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:golfnews-10kpmf6", name: "GolfNews", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "no_epg_sport", logoUrl: "https://i.ibb.co/488srb1/Golf-News-BEARTV.png", isHd: false, hasInitialStream: true },
  { canonicalKey: "tv:fightbox-hd-hrkam6", name: "FightBox HD", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "fightbox-hd", logoUrl: "https://i.imgur.com/mRsnztA.png", isHd: true, hasInitialStream: true },
  { canonicalKey: "tv:channel-065720e31f-1lfbutq", name: "Футбол", groupSlug: "international", sourceGroup: "QUỐC TẾ", tvgId: "football-ru", logoUrl: "https://i.imgur.com/pEuaZVx.png", isHd: false, hasInitialStream: true },
];
